### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Naveenreddy7571** [libredeb/comice-control-center#5]
i installed and just ran it  its not working'

**Comment by natone2** [comment]
can u tell me what problem u have?

**Comment by natone2** [comment]
> i installed and just ran it its not working'

can u tell me what problem u have?

**Comment by natone2** [comment]
> > i installed and just ran it its not working'
> 
> can u tell me what problem u have?

if u want u can check my revision of the app

**Comment by libredeb** [comment]
I was able to replicate and experience the same error... I added extra and much clearer instructions to the documentation.
